apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vfcd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vfcd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vfcd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vfcd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vfcd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kqpc-tenant/rhtap-demo-app/hacbs-test-project-vfcd@sha256:95ba85088cdec46d4805d7ddf1f10072a32516baa93a12e89371939fc370c801
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
